#include "stdafx.h"
#include "CRRCmdDefs.h"
//
const int CRCMDSN_INVALID = -1;
//
const int CRCMDTYPE_UNKNOWN = -1;
const int CRCMDTYPE_REQ_LOGIN = 1;
const int CRCMDTYPE_ACK_LOGIN = 2;
const int CRCMDTYPE_REQ_LOGOFF = 3;
const int CRCMDTYPE_ACK_LOGOFF = 4;
const int CRCMDTYPE_REQ_ACCOUNT_REG = 5;
const int CRCMDTYPE_ACK_ACCOUNT_REG = 6;
const int CRCMDTYPE_REQ_PRODUCT_PUBLISH = 11;
const int CRCMDTYPE_ACK_PRODUCT_PUBLISH = 12;
const int CRCMDTYPE_REQ_ADD_ATTETION = 13;
const int CRCMDTYPE_ACK_ADD_ATTETION = 14;
const int CRCMDTYPE_REQ_FETCH_ATTETION_LIST = 15;
const int CRCMDTYPE_ACK_FETCH_ATTETION_LIST = 16;
const int CRCMDTYPE_REQ_FETCH_ACCOUNT_INFO = 17;
const int CRCMDTYPE_ACK_FETCH_ACCOUNT_INFO = 18;
const int CRCMDTYPE_REQ_FETCH_ACCOUNT_PRODUCTS = 19;
const int CRCMDTYPE_ACK_FETCH_ACCOUNT_PRODUCTS = 20;
const int CRCMDTYPE_REQ_FETCH_ATTETIONED_LIST = 21;
const int CRCMDTYPE_ACK_FETCH_ATTETIONED_LIST = 22;





