#ifndef __CRRCMDDEFS_H__
#define __CRRCMDDEFS_H__
#include "tchar.h"
//
extern const int CRCMDSN_INVALID;
//
extern const int CRCMDTYPE_UNKNOWN;
extern const int CRCMDTYPE_REQ_LOGIN;
extern const int CRCMDTYPE_ACK_LOGIN;
extern const int CRCMDTYPE_REQ_LOGOFF;
extern const int CRCMDTYPE_ACK_LOGOFF;
extern const int CRCMDTYPE_REQ_ACCOUNT_REG;
extern const int CRCMDTYPE_ACK_ACCOUNT_REG;
extern const int CRCMDTYPE_REQ_PRODUCT_PUBLISH;
extern const int CRCMDTYPE_ACK_PRODUCT_PUBLISH;
extern const int CRCMDTYPE_REQ_ADD_ATTETION;
extern const int CRCMDTYPE_ACK_ADD_ATTETION;
extern const int CRCMDTYPE_REQ_FETCH_ATTETION_LIST;
extern const int CRCMDTYPE_ACK_FETCH_ATTETION_LIST;
extern const int CRCMDTYPE_REQ_FETCH_ACCOUNT_INFO;
extern const int CRCMDTYPE_ACK_FETCH_ACCOUNT_INFO;
extern const int CRCMDTYPE_REQ_FETCH_ACCOUNT_PRODUCTS;
extern const int CRCMDTYPE_ACK_FETCH_ACCOUNT_PRODUCTS;
extern const int CRCMDTYPE_REQ_FETCH_ATTETIONED_LIST;
extern const int CRCMDTYPE_ACK_FETCH_ATTETIONED_LIST;



#endif //__CRRCMDDEFS_H__