#ifndef __HMNWEENVCFG_H__
#define __HMNWEENVCFG_H__
#include "winsock2.h"
//
#define HMNWE_NAMESPACE_BEGIN namespace hmnwe {
#define HMNWE_NAMESPACE_END };
#define USING_NAMESPACE_HMNWE using namespace hmnwe;
//
#ifdef HMNWE_EXPORTS
#define HMNWE_API __declspec(dllexport)
#else
#define HMNWE_API __declspec(dllimport)
#endif //HMNWE_EXPORTS
//
#define BUFSIZE_RECV_NWDATA (1024)
#define BUFSIZE_SEND_NWDATA (BUFSIZE_RECV_NWDATA)
#define BUFSIZE_ACCEPT_NWDATA (1024+512)
//
enum ENUMIOEVENTTYPE4SERVER {
	EIOEVENT4SERVER_TYPE_UNKNOWN = -1,
	EIOEVENT4SERVER_TYPE_ACCEPT = 0,
	EIOEVENT4SERVER_TYPE_RECV,
	EIOEVENT4SERVER_TYPE_SEND,
};
//
enum ENUMIOEVENTTYPE4CLIENT {
	EIOEVENT4CLIENT_TYPE_UNKNOWN = -1,
	EIOEVENT4CLIENT_TYPE_CONNECT = 0,
	EIOEVENT4CLIENT_TYPE_RECV,
	EIOEVENT4CLIENT_TYPE_SEND,
};
//
#endif //__HMNWEENVCFG_H__
