#ifndef __CRMODULEIDDEFS_H__
#define __CRMODULEIDDEFS_H__

enum ENUMCRMODULEID {
	ECRMODULE_ID_BEGIN = 0,
    ECRMODULE_ID_CMDDISPATCH,
	ECRMODULE_ID_ACCOUNTMGR,
	ECRMODULE_ID_PRODUCTMGR,
};


#endif //__CRMODULEIDDEFS_H__